// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PaymentSystem.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CashInPaymentSystem.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CashInPaymentSystem
    {
        [EnumMember(Value = "Unknown")]
        Unknown,
        [EnumMember(Value = "CreditVoucher")]
        CreditVoucher,
        [EnumMember(Value = "Bitcoin")]
        Bitcoin,
        [EnumMember(Value = "Ethereum")]
        Ethereum,
        [EnumMember(Value = "Swift")]
        Swift,
        [EnumMember(Value = "SolarCoin")]
        SolarCoin,
        [EnumMember(Value = "ChronoBank")]
        ChronoBank,
        [EnumMember(Value = "Fxpaygate")]
        Fxpaygate,
        [EnumMember(Value = "Quanta")]
        Quanta
    }
    internal static class CashInPaymentSystemEnumExtension
    {
        internal static string ToSerializedValue(this CashInPaymentSystem? value)
        {
            return value == null ? null : ((CashInPaymentSystem)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CashInPaymentSystem value)
        {
            switch( value )
            {
                case CashInPaymentSystem.Unknown:
                    return "Unknown";
                case CashInPaymentSystem.CreditVoucher:
                    return "CreditVoucher";
                case CashInPaymentSystem.Bitcoin:
                    return "Bitcoin";
                case CashInPaymentSystem.Ethereum:
                    return "Ethereum";
                case CashInPaymentSystem.Swift:
                    return "Swift";
                case CashInPaymentSystem.SolarCoin:
                    return "SolarCoin";
                case CashInPaymentSystem.ChronoBank:
                    return "ChronoBank";
                case CashInPaymentSystem.Fxpaygate:
                    return "Fxpaygate";
                case CashInPaymentSystem.Quanta:
                    return "Quanta";
            }
            return null;
        }

        internal static CashInPaymentSystem? ParseCashInPaymentSystem(this string value)
        {
            switch( value )
            {
                case "Unknown":
                    return CashInPaymentSystem.Unknown;
                case "CreditVoucher":
                    return CashInPaymentSystem.CreditVoucher;
                case "Bitcoin":
                    return CashInPaymentSystem.Bitcoin;
                case "Ethereum":
                    return CashInPaymentSystem.Ethereum;
                case "Swift":
                    return CashInPaymentSystem.Swift;
                case "SolarCoin":
                    return CashInPaymentSystem.SolarCoin;
                case "ChronoBank":
                    return CashInPaymentSystem.ChronoBank;
                case "Fxpaygate":
                    return CashInPaymentSystem.Fxpaygate;
                case "Quanta":
                    return CashInPaymentSystem.Quanta;
            }
            return null;
        }
    }
}
