// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PaymentSystem.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PaymentUrlDataResponse
    {
        /// <summary>
        /// Initializes a new instance of the PaymentUrlDataResponse class.
        /// </summary>
        public PaymentUrlDataResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentUrlDataResponse class.
        /// </summary>
        /// <param name="paymentSystem">Possible values include: 'Unknown',
        /// 'CreditVoucher', 'Bitcoin', 'Ethereum', 'Swift', 'SolarCoin',
        /// 'ChronoBank', 'Fxpaygate', 'Quanta'</param>
        public PaymentUrlDataResponse(CashInPaymentSystem paymentSystem, string paymentUrl = default(string), string okUrl = default(string), string failUrl = default(string), string reloadRegexp = default(string), string urlsRegexp = default(string), string errorMessage = default(string))
        {
            PaymentUrl = paymentUrl;
            OkUrl = okUrl;
            FailUrl = failUrl;
            ReloadRegexp = reloadRegexp;
            UrlsRegexp = urlsRegexp;
            ErrorMessage = errorMessage;
            PaymentSystem = paymentSystem;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PaymentUrl")]
        public string PaymentUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OkUrl")]
        public string OkUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FailUrl")]
        public string FailUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ReloadRegexp")]
        public string ReloadRegexp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UrlsRegexp")]
        public string UrlsRegexp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'CreditVoucher',
        /// 'Bitcoin', 'Ethereum', 'Swift', 'SolarCoin', 'ChronoBank',
        /// 'Fxpaygate', 'Quanta'
        /// </summary>
        [JsonProperty(PropertyName = "PaymentSystem")]
        public CashInPaymentSystem PaymentSystem { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
