// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PaymentSystem.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PaymentLimitsResponse
    {
        /// <summary>
        /// Initializes a new instance of the PaymentLimitsResponse class.
        /// </summary>
        public PaymentLimitsResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentLimitsResponse class.
        /// </summary>
        public PaymentLimitsResponse(double creditVouchersMinValue, double creditVouchersMaxValue, double fxpaygateMinValue, double fxpaygateMaxValue, double easyPaymentGatewayMinValue, double easyPaymentGatewayMaxValue)
        {
            CreditVouchersMinValue = creditVouchersMinValue;
            CreditVouchersMaxValue = creditVouchersMaxValue;
            FxpaygateMinValue = fxpaygateMinValue;
            FxpaygateMaxValue = fxpaygateMaxValue;
            EasyPaymentGatewayMinValue = easyPaymentGatewayMinValue;
            EasyPaymentGatewayMaxValue = easyPaymentGatewayMaxValue;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreditVouchersMinValue")]
        public double CreditVouchersMinValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CreditVouchersMaxValue")]
        public double CreditVouchersMaxValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FxpaygateMinValue")]
        public double FxpaygateMinValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FxpaygateMaxValue")]
        public double FxpaygateMaxValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EasyPaymentGatewayMinValue")]
        public double EasyPaymentGatewayMinValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EasyPaymentGatewayMaxValue")]
        public double EasyPaymentGatewayMaxValue { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
