// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.PaymentSystem.Client.AutorestClient.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SourceClientInfoResponse
    {
        /// <summary>
        /// Initializes a new instance of the SourceClientInfoResponse class.
        /// </summary>
        public SourceClientInfoResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SourceClientInfoResponse class.
        /// </summary>
        public SourceClientInfoResponse(string sourceClientId)
        {
            SourceClientId = sourceClientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SourceClientId")]
        public string SourceClientId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SourceClientId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SourceClientId");
            }
        }
    }
}
